version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:8.0.22
    container_name: your_container_name
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --secure-file-priv=""
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      # - MYSQL_DATABASE # コンテナ生成時にデータベースを作成する場合
    ports:
      - 12345:3306
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d
      - ./mysql_data:/var/lib/mysql
    restart: always
